FROM ubuntu:18.04

RUN apt-get update \
    && apt-get -y install \
           curl \
           dnsutils \
           grep \
           iputils-ping \
           git \
           jq \
           lsof \
           less \
           mtr \
           net-tools \
           netcat-openbsd \
           procps \
           wget

CMD ["bash"]
